title: "techblog"
baseurl: "/techblog"
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
permalink: pretty

collections:
  dev_pages:
    output: true
    permalink: /:collection/:path/

highlight:
  highlighter: rouge
  theme: github
